mysql:
  image: mysql_ems
  ports:
    - "3308:3306"
  environment:
    - MYSQL_USER=root
    - MYSQL_DATABASE=test
    - MYSQLPASSWORD=root


AppServer:
  image: java_ems_demo
  ports:
    - "8006:8080"
  environment:
    - database_driverClassName=com.mysql.jdbc.Driver
    - database_url=jdbc:mysql://172.27.59.8:3308/test
    - database_username=root
    - database_password=root


